name: supertokens
description: SuperTokens session management implementation for Flutter apps
version: 0.0.1
author: supertokens
homepage: https://supertokens.io/

environment:
  sdk: ">=1.22.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.1
  cookie_jar: 2.0.0
  shared_preferences: 2.0.5
  mutex: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

