version: 2.1
orbs:
  continuation: circleci/continuation@0.1.2
  slack: circleci/slack@3.4.2
  jq: circleci/jq@2.2.0
jobs:
  publish:
    docker: 
      - image: rishabhpoddar/supertokens_flutter_sdk_testing
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mkdir temp
      - run: cp CHANGELOG.md temp/CHANGELOG.md
      - run: cp README.md temp/README.md
      - run: cp LICENSE temp/LICENSE
      - run: cp CONTRIBUTING.md temp/CONTRIBUTING.md
      - run: cp -r lib/ temp/lib/
      - run: cp pubspec.yaml temp/pubspec.yaml
      - run:
          name: Setup pub.dev login
          command: cd .circleci && ./setupPubLogin.sh
      - run: cd temp && flutter pub publish
      - run: rm ~/.pub-cache/credentials.json
  test:
    docker: 
      - image: rishabhpoddar/supertokens_flutter_sdk_testing
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Generate config
          command: cd .circleci && ./generateConfig.sh
      - continuation/continue:
          configuration_path: .circleci/config_continue.yml

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          context:
              - slack-notification
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/